// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { clientLoader as loader_1 } from '/Users/heixing/Git/ditejs/ssr-umi/src/pages/index.tsx';
import { clientLoader as loader_2 } from '/Users/heixing/Git/ditejs/ssr-umi/src/pages/users.tsx';
import { clientLoader as loader_3 } from '/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user2.tsx';
import { clientLoader as loader_4 } from '/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user2/info.tsx';
import { clientLoader as loader_5 } from '/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user.tsx';
export default {
  'index': loader_1,
  'users': loader_2,
  'users/user2': loader_3,
  'users/user2/info': loader_4,
  'users/user': loader_5,
};
