// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import clientLoaders from './loaders.js';
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"posts/post":{"path":"posts/post","id":"posts/post","file":"posts/post.tsx","hasServerLoader":false,"clientLoader":clientLoaders['posts/post']},"index":{"path":"/","id":"index","file":"index.tsx","hasServerLoader":true,"clientLoader":clientLoaders['index']},"users":{"path":"users","id":"users","file":"users.tsx","hasServerLoader":true,"clientLoader":clientLoaders['users']},"users/user2":{"path":"user2","id":"users/user2","parentId":"users","file":"users/user2.tsx","hasServerLoader":true,"clientLoader":clientLoaders['users/user2']},"users/user2/info":{"path":"info","id":"users/user2/info","parentId":"users/user2","file":"users/user2/info.tsx","hasServerLoader":true,"clientLoader":clientLoaders['users/user2/info']},"users/user":{"path":"user","id":"users/user","parentId":"users","file":"users/user.tsx","hasServerLoader":true,"clientLoader":clientLoaders['users/user']}},
    routeComponents: {
'posts/post': React.lazy(() => import(/* webpackChunkName: "src__pages__posts__post" */'../../../src/pages/posts/post.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'users': React.lazy(() => import(/* webpackChunkName: "src__pages__users" */'../../../src/pages/users.tsx')),
'users/user2': React.lazy(() => import(/* webpackChunkName: "src__pages__users__user2" */'../../../src/pages/users/user2.tsx')),
'users/user2/info': React.lazy(() => import(/* webpackChunkName: "src__pages__users__user2__info" */'../../../src/pages/users/user2/info.tsx')),
'users/user': React.lazy(() => import(/* webpackChunkName: "src__pages__users__user" */'../../../src/pages/users/user.tsx')),
},
  };
}
