// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { getClientRootComponent } from '/Users/heixing/Git/ditejs/ssr-umi/node_modules/@umijs/renderer-react/dist/server.js';
import { getRoutes } from './core/route';
import { PluginManager } from '/Users/heixing/Git/ditejs/ssr-umi/node_modules/umi/client/client/plugin.js';
import createRequestHandler from '/Users/heixing/Git/ditejs/ssr-umi/node_modules/@umijs/server/dist/ssr.js';

const routesWithServerLoader = {
  'index': () => import('/Users/heixing/Git/ditejs/ssr-umi/src/pages/index.tsx'),
  'users': () => import('/Users/heixing/Git/ditejs/ssr-umi/src/pages/users.tsx'),
  'users/user2': () => import('/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user2.tsx'),
  'users/user2/info': () => import('/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user2/info.tsx'),
  'users/user': () => import('/Users/heixing/Git/ditejs/ssr-umi/src/pages/users/user.tsx'),
};

// TODO: support runtime plugins
export function getPlugins() {
  return [];
}

export function getValidKeys() {
  return ['patchRoutes','patchClientRoutes','modifyContextOpts','rootContainer','innerProvider','i18nProvider','accessProvider','dataflowProvider','outerProvider','render','onRouteChange',];
}

export function getManifest() {
  return JSON.parse(require('fs').readFileSync('/Users/heixing/Git/ditejs/ssr-umi/dist/build-manifest.json', 'utf-8'));
}

// TODO: remove global variable
global.g_getAssets = (fileName) => {
  let m = typeof manifest === 'function' ? manifest() : manifest;
  return m.assets[fileName];
};

const manifest = "production" === 'development' ? getManifest : getManifest();
const requestHandler = createRequestHandler({
  routesWithServerLoader,
  PluginManager,
  getPlugins,
  getValidKeys,
  getRoutes,
  manifest,
  getClientRootComponent,
});

export default requestHandler;
